name: build project
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: bazelisk build //...